const PRODUCT_DATA = [
    {
      title: 'mens',
      items: [
        {
          id: 1,
          name: 'HANES T Shirts - Size XL',
          imageUrl: 'https://i.ibb.co/GCc47cw/Hanes-2-XL-tagless-t-shirts-price-9-00-quantity-2.jpg',
          price: 15.00,
          shipping: 0,
          quantity: 999,
          description: 'HANES Mens Tagless T Shirt, Size XL, 2 Pack~Blue/Black',
          title: 'mens',
        },
        {
          id: 2,
          name: 'HANES T Shirts - Size L',
          imageUrl: 'https://i.ibb.co/gy6w2hg/Hanes-2-Large-tagless-t-shirts-price-7-90-quantity-1.jpg',
          price: 14.00,
          shipping: 0,
          quantity: 999,
          description: 'HANES Mens Tagless T Shirt, Size L, 2 Pack~Blue',
          title: 'mens',
        },
        {
          id: 3,
          name: 'HANES T Shirts - Size M',
          imageUrl: 'https://i.ibb.co/D73VYCm/Hanes-2-M-tagless-t-shirts-price-9-00-quantity-1.jpg',
          price: 15.00,
          shipping: 0,
          quantity: 999,
          description: 'HANES Mens Tagless T Shirt, Size M, 2 Pack~Blue, Black',
          title: 'mens',
        },
        {
          id: 4,
          name: 'Hanes White Briefs Underwear - Size S',
          imageUrl: 'https://i.ibb.co/2dn7Jwy/Hanes-5-Pk-white-Tagless-Comfort-Soft-Mens-Briefs-Size-S-28-30.jpg',
          price: 10,
          shipping: 0,
          quantity: 999,
          description: "Hanes 5 Pk white Tagless Comfort Soft Mens' Briefs Size S (28-30)",
          title: 'mens',
        },
        {
          id: 5,
          name: 'Hanes Boxers Underwear - Size: 2XL',
          imageUrl: 'https://i.ibb.co/WtcgPHg/Hanes-2-XL-Men-s-Blue-Boxers-Underwear-2-Pack-Tagless.jpg',
          price: 24.00,
          shipping: 0,
          quantity: 999,
          description: "Hanes 2XL Men's Blue Boxers Underwear - 2-Pack Tagless Best Fit Boxers, Size: 2XL/44-46. Tagless. Cotton. Lot of 2 Bags for Total of 4 Pairs of Underwear.",
          title: 'mens',
        },
        {
          id: 6,
          name: 'Hanes Pocket T-Shirts - Size: M',
          imageUrl: 'https://i.ibb.co/mXwgZ3T/Hanes-2-Pack-Men-s-Comfort-Soft-Tagless-Pocket-T-Shirts-Size-38-40-Medium.jpg',
          price: 25.00,
          shipping: 0,
          quantity: 999,
          description: "Hanes 2-Pack Men's ComfortSoft Tagless Pocket T-Shirts. Size M: 38-40. Colors: Black and Grey. Cotton Crew Neck. Lot of 2 for a Total of 4 Shirts.",
          title: 'mens',
        },
        {
          id: 7,
          name: 'Hanes Boxer Brief Underwear - Size: M',
          imageUrl: 'https://i.ibb.co/cwN94ZC/Hanes-2-Pack-Mens-s-Tagless-Boxer-Brief-Underwear-Size-M.jpg',
          price: 20.00,
          shipping: 0,
          quantity: 999,
          description: "Hanes 2-Pack Men's Tagless Boxer Brief Underwear. Size: M. Multicolor Soft Wicking Fabric. Lot of 2 for Total of 4 Pairs of Underwear.",
          title: 'mens',
        },
        {
          id: 8,
          name: 'Hanes Stretch Boxers - Size: S',
          imageUrl: 'https://i.ibb.co/D8RtMdR/Hanes-Mens-2-Pack-Tagless-Stretch-Boxers-Comfort-Flex-Waist-Size-S-28-30.jpg',
          price: 24.00,
          shipping: 0,
          quantity: 999,
          description: 'Lot of 3 Bags of Hanes Mens 2 Pack Tagless Stretch Boxers Underwear. Size: S 28-30. Total: 6 Pairs of Underwear. Comfort Flex Waist. Multiple Colors.',
          title: 'mens',
        },
        {
          id: 9,
          name: 'Hanes Boxer Brief Underwear - Size S',
          imageUrl: 'https://i.ibb.co/5nzGrmJ/Hanes-Mens-Cool-Comfort-Boxer-Brief-Underwear-Size-S-28-30.jpg',
          price: 29.00,
          shipping: 0,
          quantity: 999,
          description: 'Hanes Mens Cool Comfort Boxer Briefs Underwear. Size S 28-30". 2-Pack Each. Lot of 3. Total of 6 Underwear. Colors: Black and Grey.',
          title: 'mens',
        },
        {
            id: 10,
            name: 'Hanes Tartan Boxers Underwear - Size M',
            imageUrl: 'https://i.ibb.co/DfWL6C4/Hanes-Men-s-Tartan-Boxers-Underwear-Size-M.jpg',
            price: 11.00,
            shipping: 0,
            quantity: 999,
            description: "Hanes Men's Tartan Boxers Underwear. Size M. 32 - 34 Comfort Flex Waistband. 2-Pack.",
            title: 'mens',
        },
        {
            id: 11,
            name: 'Hanes Mesh Boxer Briefs - Size: M',
            imageUrl: 'https://i.ibb.co/D8HhW9v/Hanes-Medium-Lightweight-Mesh-Boxer-Briefs-Underwear-Size-M-32-34.jpg',
            price: 20.00,
            shipping: 0,
            quantity: 999,
            description: 'Lot of 2 Hanes Medium 2-Pack Tagless Lightweight Mesh Boxer Briefs. Size: M 32-34". Total of 4 Pairs of Underwear.',
            title: 'mens',
        },
        {
            id: 12,
            name: 'Mission Ridge Denim Blue Jeans, 34 X 30',
            imageUrl: 'https://i.ibb.co/sPGM9Wr/Men-s-Mission-Ridge-Denim-Blue-Jeans-Size-34-X-30.jpg',
            price: 20.00,
            shipping: 0,
            quantity: 999,
            description: "Men's Mission Ridge Denim Blue Jeans. 5 Pocket. Light Blue Wash. Size: 34 X 30.",
            title: 'mens',
        },
        
      ],
    },
    {
      title: 'womens',
      items: [
        {
          id: 13,
          name: "Hanes Women's Boy Briefs - Size M/6",
          imageUrl: 'https://i.ibb.co/tKpzkcd/3-Pack-Hanes-Women-s-Tagless-Boy-Briefs-Sport-Styling-Size.jpg',
          price: 20.00,
          shipping: 0,
          quantity: 999,
          description: "3 Pack of Hanes Women's Tagless Boy Briefs Underwear - Sport Styling Size M/6 (3Pairs a Pack).  Total of 9 pairs of underwar.",
          title: 'womens',
        },
        {
          id: 14,
          name: 'Hanes White Ankle Socks - Size 5 - 9',
          imageUrl: 'https://i.ibb.co/xDNzN4D/Hanes-6-Pack-Pairs-Women-s-White-Ankle-Socks-Size-5-9.jpg',
          price: 10.00,
          shipping: 0,
          quantity: 999,
          description: "Hanes 6 Pack Pairs Women's White Ankle Socks - Size 5-9.  Ankle High White Socks.",
          title: 'womens',
        },
        {
          id: 15,
          name: 'Hanes White Crew Socks - Size 8-12.',
          imageUrl: 'https://i.ibb.co/RQcxq8P/Hanes-Women-s-White-Extended-Size-Crew-Socks-Shoe-Size-8-12.jpg',
          price: 17.00,
          shipping: 0,
          quantity: 999,
          description: "Hanes 8-Pack Women's White Extended Size Crew Socks. Shoe Size 8-12.",
          title: 'womens',
        },
        {
          id: 16,
          name: 'Hanes No Show White Socks - Size: 8-12',
          imageUrl: 'https://i.ibb.co/chQmpJ9/Hanes-Women-s-No-Show-White-Socks-Shoe-Size-8-12.jpg',
          price: 21.99,
          shipping: 0,
          quantity: 999,
          description: "2 Packages of Hanes Women's No Show White Socks. Shoe Size: 8-12. Value 8 Pack. Total of 16 Pairs of Socks.",
          title: 'womens',
        },
      ],
    },
    {
      title: 'childrens',
      items: [
        {
          id: 17,
          name: "Zara Girl's Multicolor Dress",
          imageUrl: 'https://i.ibb.co/6F7WShy/Zara-Girls-Multicolor-Knee-Length-Dress-For-13-14.jpg',
          price: 30,
          shipping: 0,
          quantity: 999,
          description: "Zara Girl's Dress for 13 - 14 Years of Age.  Multicolor, Knee Length, New with tags",
          title: 'childrens',
        },
        {
          id: 18,
          name: "Zara Girl's Brown Dress",
          imageUrl: 'https://i.ibb.co/WF2T3GK/Zara-Girls-Brown-Knee-Length-Dress-For-13-14-Years-of-Age.jpg',
          price: 30.00,
          shipping: 0,
          quantity: 999,
          description: "Zara Girl's Dress for 13 - 14 Years of Age.  Brown. Knee Length. Size: XS. New with tags",
          title: 'childrens',
        },
        {
          id: 19,
          name: 'Hanes Girls Low Rise Briefs - Size: 10',
          imageUrl: 'https://i.ibb.co/3cLZPS3/Hanes-6-Pack-Girls-Tagless-Low-Rise-Briefs-Panties-Size-10.jpg',
          price: 15.00,
          shipping: 0,
          quantity: 999,
          description: 'Hanes 6-Pack Girls Tagless Low Rise Briefs Panties, Size: 10. Assorted Colors. 2 Bags in each Order for Total of 12 Pairs of Underwear. Machine Washable Cotton. Tagless.',
          title: 'childrens',
        },
        {
          id: 20,
          name: 'Hanes Boys Size M T Shirts',
          imageUrl: 'https://i.ibb.co/0YKS9kh/Hanes-Boys-2-Pack-Tagless-T-Shirts-Navy-Blue-Gray-Size-M-10-12.jpg',
          price: 17.35,
          shipping: 0,
          quantity: 999,
          description: 'Hanes Boys 2 Pack Tagless T-Shirts Navy Blue & Gray, Size M 10-12. Crew Neck Style and Cotton Fabric. Total of 4 Shirts in Lot.',
          title: 'childrens',
        },
        {
          id: 21,
          name: 'Girls Basics Underwear Panties - Size 10',
          imageUrl: 'https://i.ibb.co/1fqwwBK/Girls-Basics-Underwear-Panties-Size-10-2-packs-of-5-pair-each.jpg',
          price: 12.00,
          shipping: 0,
          quantity: 999,
          description: 'Girls Basics Underwear Panties. Size 10. Material: Cotton. 2 Packages of 5 Pack of Briefs for Total of 10 Pair. Colors: Pink, Blue, and White.',
          title: 'childrens',
        },
        {
          id: 22,
          name: "Hanes Girl's Panty Briefs - Size 14",
          imageUrl: 'https://i.ibb.co/yQSD4gK/Hanes-Pre-Shrunk-Girl-s-Underwear-Panty-Briefs-Size-14-6-Pack-Multi-Color-Briefs-Tagless.jpg',
          price: 16.00,
          shipping: 0,
          quantity: 999,
          description: "Hanes Pre-Shrunk Girl's Underwear Panty Briefs. Size 14. 6 Pack. Multicolor. Tagless. Cotton.",
          title: 'childrens',
        },
        {
            id: 23,
            name: 'Hanes Boys Briefs - Size: Small 6-8.',
            imageUrl: 'https://i.ibb.co/MRTkStF/Hanes-Boys-Briefs-Size-Small-6-8.jpg',
            price: 17.00,
            shipping: 0,
            quantity: 999,
            description: 'Hanes Boys Briefs. Size: Small 6-8. Tagless. Multiple Colors. Cotton. 4 Pairs of Underwear per Package. Lot of 2 Bags.',
            title: 'childrens',
        },
        {
            id: 24,
            name: 'Hanes Girls Low Rise Briefs - Size: 12',
            imageUrl: 'https://i.ibb.co/9Yj8zJ0/Hanes-Girls-Low-Rise-Cotton-Briefs-Underwear-Size-12-Tagless-6-Pairs-Panties.jpg',
            price: 16.00,
            shipping: 0,
            quantity: 999,
            description: 'Lot of 2 New Packages of Hanes Size 12 Girls Low Rise Cotton Briefs Underwear. 6-Pack in Each Package. Tagless. Total of 12 Pairs of Underwear.',
            title: 'childrens',
        },
      ],
    },
    {
      title: 'toys',
      items: [
        {
            id: 25,
            name: 'LEGO Jurassic World',
            imageUrl: 'https://i.ibb.co/zsXnYWR/LEGO-Jurassic-World-Gallimimus-and-Pteranodon-Breakout.jpg',
            price: 19.00,
            shipping: 0,
            quantity: 999,
            description: "LEGO Jurassic World: Gallimimus and Pteranodon Breakout. Age: 7+. Product Information: Kids can build their own LEGO Jurassic World of dinosaur-chasing action with this Gallimimus and Pteranodon Breakout toy playset. It features a toy research vehicle with a dual minifigure cockpit, net shooter, 2 detachable drones, a removable mini lab and lots of accessory elements to inspire hours of creative solo or social play. Role-play adventures This building set for kids also includes 3 LEGO Jurassic World minifigures and an awesome Gallimimus dinosaur figure and Pteranodon toy figure to role-play exciting adventures. Clear, illustrated instructions mean that even if your youngster is new to LEGO toys, they can build with confidence right away. Dinosaur fun! Featuring molded, buildable dinosaur figures, minifigures, detailed vehicles and more, LEGO Jurassic World construction toys make awesome birthday presents for kids and fans of all ages. They can relive scenes from the animated series and movies, create new stories or just display the collectible models.",
            title: 'toys',
        },
        {
            id: 26,
            name: 'Barbie 2020 FASHIONISTAS DOLL',
            imageUrl: 'https://i.ibb.co/JmmxFfs/Barbie-2020-FASHIONISTAS-DOLL-140-with-Long-Brunette-Hair-Mouse-Print-Dress.jpg',
            price: 18.00,
            shipping: 0,
            quantity: 999,
            description: 'Barbie 2020 FASHIONISTAS DOLL #140 with Long Brunette Hair & Mouse-Print Dress. Age Level: 3+.',
            title: 'toys',
        },
        {
          id: 27,
          name: 'Classic Wooden Chess Set',
          imageUrl: 'https://i.ibb.co/jrXJnTg/Classic-Wooden-Chess-Set.jpg',
          price: 22.00,
          shipping: 0,
          quantity: 999,
          description: 'Solid Wooden Chess Set in Natural Finish',
          title: 'toys',
        },
        {
          id: 28,
          name: 'Nickelodeon Blues Clues PIRATE EDITION',
          imageUrl: 'https://i.ibb.co/xCRHpd2/Nickelodeon-Blues-Clues-You-PIRATE-EDITION.jpg',
          price: 17.00,
          shipping: 0,
          quantity: 999,
          description: 'Nickelodeon Blues Clues & You PIRATE EDITION 4 pc Figure Set. Interactive Figures. Age: 3 - 4 Years Old.',
          title: 'toys',
        },
        {
          id: 29,
          name: 'Cribmates Plush Doll Teether',
          imageUrl: 'https://i.ibb.co/17w6Xbf/Cribmates-Plush-Doll-Teether-Wild-Free-Fox-Plush-Crinkle-Toy.jpg',
          price: 14.99,
          shipping: 0,
          quantity: 999,
          description: 'Cribmates Plush Doll Teether Wild & Free Fox Plush Crinkle Toy. Age: 0+ Months',
          title: 'toys',
        },
        {
            id: 30,
            name: 'Disney Frozen II Seven Piece Playset',
            imageUrl: 'https://i.ibb.co/9TBR4Dz/Disney-Frozen-II-Seven-Piece-Playset.jpg',
            price: 18.99,
            shipping: 0,
            quantity: 999,
            description: 'Disney Frozen II Seven Piece Playset. Petite Anna and Olaf Ice Canoe Gift Set.',
            title: 'toys',
        },
        {
            id: 31,
            name: 'Remote Controlled Speed Boat',
            imageUrl: 'https://i.ibb.co/ZTvzxbw/Speed-Boat-Radio-Remote-Controlled-Battery-Black-with-Red-and-Silver-Strips.jpg',
            price: 17.50,
            shipping: 0,
            quantity: 999,
            description: 'Speed Boat Radio Remote Controlled Battery Black with Red and Silver Strips. Required Assembly:	Ready to Go/RTR/RTF (All included). Age Level: 3 - 11 Years',
            title: 'toys',
        },
        {
            id: 32,
            name: 'Hedbanz Disney Frozen Card Game',
            imageUrl: 'https://i.ibb.co/5LcgCTK/headbanz-frozen-price-9-0-quantity-1.jpg',
            price: 15.10,
            shipping: 0,
            quantity: 999,
            description: `Children's guessing game "Who am I?" themed to Disney's Frozen.  Ages 6+`,
            title: 'toys',
        },
        {
            id: 33,
            name: 'Disney Hedbanz Guessing Card Game',
            imageUrl: 'https://i.ibb.co/JQVbVZy/Disney-Hedbanz-Guessing-Card-Game-price-9-90-quantity-1.jpg',
            price: 13.00,
            shipping: 0,
            quantity: 999,
            description: `Disney themed Children's guessing game "Who am I?".  Ages 6+`,
            title: 'toys',
        },
        {
            id: 34,
            name: 'POOL CANDY Inflatable Pool Float',
            imageUrl: 'https://i.ibb.co/wpppqLY/POOL-CANDY-Inflatable-Pool-Float-Glitter-Seahorse-Horse.jpg',
            price: 25.50,
            shipping: 0,
            quantity: 999,
            description: 'POOL CANDY Inflatable Pool Float Glitter Seahorse Horse. Size: Jumbo.',
            title: 'toys',
        },
        {
            id: 35,
            name: 'Lego City Vehicles 2 in 1',
            imageUrl: 'https://i.ibb.co/M5vPtgk/Lego-City-Vehicles-2-in-1-Gift-Set.jpg',
            price: 37.00,
            shipping: 0,
            quantity: 999,
            description: 'Lego City Vehicle Set. Age Level: 5+',
            title: 'toys',
        },
        {
            id: 36,
            name: 'Disney Junior Mickey on the Move Car',
            imageUrl: 'https://i.ibb.co/F8SFWBk/Disney-Junior-Mickey-on-the-Move-Vehicle.jpg',
            price: 14.00,
            shipping: 0,
            quantity: 999,
            description: 'Disney Junior Mickey on the Move Vehicle. Poseable Mickey Mouse Daily Driver',
            title: 'toys',
        },
        {
            id: 37,
            name: 'Funko Marvel Battleworld Series 2',
            imageUrl: 'https://i.ibb.co/RzJt12H/Funko-Marvel-Battleworld-Series-2.jpg',
            price: 19.00,
            shipping: 0,
            quantity: 999,
            description: 'Funko Marvel Battleworld Series 2. Iron Man Mega Pack. Treachery At Twilight. Age: 6+',
            title: 'toys',
        },
        
      ],
      
    },
    {
      title: 'toiletries',
      items: [
        {
          id: 38,
          name: 'Daisy Love Marc Jacobs Perfume',
          imageUrl: 'https://i.ibb.co/9G0SyZ2/Daisy-Love-Marc-Jacobs-Perfume-price-59-quantity-4.jpg',
          price: 59.00,
          shipping: 0,
          quantity: 999,
          description: 'Daisy Love Marc Jacobs Perfume Spray-1.7 Oz Eau De Toilette. Still SEALED in package.',
          title: 'toiletries',
        },
        {
            id: 39,
            name: 'HELLO by LIONEL RICHIE Cologne',
            imageUrl: 'https://i.ibb.co/BLQyMsL/HELLO-by-LIONEL-RICHIE-Cologne-Spray-for-Men.jpg',
            price: 30.00,
            shipping: 0,
            quantity: 999,
            description: 'HELLO by LIONEL RICHIE Cologne Spray for Men, Size: 1.7 oz, 50 ml. New Sealed in Box.',
            title: 'toiletries',
          },
          {
            id: 40,
            name: "Elle L'Edition Eau De Parfum",
            imageUrl: 'https://i.ibb.co/HrDs7Nh/Elle-L-Edition-Eau-De-Parfum-1fl-oz.jpg',
            price: 29.99,
            shipping: 0,
            quantity: 999,
            description: "Elle L'Edition Eau De Parfum. Size: 1 fl. oz. Fruity Floral Scent.",
            title: 'toiletries',
        },
        {
          id: 41,
          name: 'Smile Direct Club Pro Whitening',
          imageUrl: 'https://i.ibb.co/MS0xWmt/Smile-Direct-Club-Pro-Whitening-price-19-quantity-1.jpg',
          price: 19.00,
          shipping: 0,
          quantity: 999,
          description: 'Smile Direct Club Pro Whitening Boost & Extend 28 Treatments',
          title: 'toiletries',
        },
        {
          id: 42,
          name: 'Smile Direct Club Teeth Whitening Strips',
          imageUrl: 'https://i.ibb.co/b5LK8xL/Smile-Direct-Club-Fast-Dissolving-Teeth-Whitening-Strips.jpg',
          price: 19.99,
          shipping: 0,
          quantity: 999,
          description: 'Smile Direct Club Fast Dissolving Teeth Whitening Strips 1 Treatment + 4 bonus whitening strips',
          title: 'toiletries',
        },
        {
          id: 43,
          name: 'Tena Intimates Maximum Pads #5',
          imageUrl: 'https://i.ibb.co/74gpFtt/Tena-Intimates-Maximum-Pads-5.jpg',
          price: 25.00,
          shipping: 0,
          quantity: 999,
          description: 'Tena Intimates Maximum Pads #5. 4 Bags per Order. 14 Count per Package. 56 Total. Bladder Control Incontinence Pads.',
          title: 'toiletries',
        },
        {
            id: 44,
            name: "Revlon Jontue Women's Perfume",
            imageUrl: 'https://i.ibb.co/ynKTcPM/Revlon-Jontue-Women-s-Eau-de-Cologne.jpg',
            price: 28.99,
            shipping: 0,
            quantity: 999,
            description: "Revlon Jontue Women's Eau de Cologne. Volume: 2.3 oz. New in Box.",
            title: 'toiletries',
        },
        {
            id: 45,
            name: 'Blistex Hemp & Shea Lip Balm',
            imageUrl: 'https://i.ibb.co/Mh3PF96/Blistex-Hemp-Shea-Hydration-2pk-Vanilla-Mint.jpg',
            price: 15.99,
            shipping: 0,
            quantity: 999,
            description: '2 Packages of Blistex Hemp & Shea Hydration 2pk Vanilla Mint & Pina Colada Lip Balm. 2 Sticks in Each Package.',
            title: 'toiletries',
        },
        {
            id: 46,
            name: "Burt's Bees Rescue Balm",
            imageUrl: 'https://i.ibb.co/BG3V1P8/Burt-s-Bees-Rescue-Balm-w-Turmeric-Cooling-Eucalyptus-Lip-Balm.jpg',
            price: 18.75,
            shipping: 0,
            quantity: 999,
            description: "3 Sticks of Burt's Bees Rescue Balm w/ Turmeric - Cooling Eucalyptus Lip Balm",
            title: 'toiletries',
        },
        {
            id: 47,
            name: 'King C. Gillette Razor and Refills',
            imageUrl: 'https://i.ibb.co/Y7gGsXC/King-C-Gillette-Neck-Razor-Handle-and-2-Blade-Refills.jpg',
            price: 12.75,
            shipping: 0,
            quantity: 999,
            description: 'King C. Gillette Neck Razor Handle and 2 Blade Refills.',
            title: 'toiletries',
        },
        
        
      ],
    },
    ,
    {
      title: 'pets',
      items: [
        {
          id: 48,
          name: 'Greenies Dental Treats 12oz Bag',
          imageUrl: 'https://i.ibb.co/7N4f5yZ/Greenies-Large-12oz-Bag-17-98.jpg',
          price: 18.98,
          shipping: 0,
          quantity: 999,
          description: "Dog dental treats. Good for your puppy's teeth. For large dogs, 50 - 100 lbs.",
          title: 'pets',
        },
        {
          id: 49,
          name: 'Greenies Adult Cat Dental Treats',
          imageUrl: 'https://i.ibb.co/nDrVP1z/Greenie-s-cat-dental-treats-4-6oz-price-9-80-quantity-9.jpg',
          price: 9.80,
          shipping: 0,
          quantity: 999,
          description: "Cat dental treats. Good for your kitty's teeth. Succulent Shrimp flavored. 4.6 oz.",
          title: 'pets',
        },
        {
          id: 50,
          name: 'Greenies Petite Dental Dog Treats',
          imageUrl: 'https://i.ibb.co/8B46tsz/Greenies-Original-Petite-Natural-Dental-Dog-price-20-99-quantity-1.jpg',
          price: 20.99,
          shipping: 0,
          quantity: 999,
          description: 'Greenies Original Petite Natural Dental Dog Treats - For smaller dogs, 15-25 lbs dogs',
          title: 'pets',
        },
        
      ],
    },
    ,
    {
      title: 'household',
      items: [
        {
          id: 51,
          name: 'WHINK The Original Hair Clog Blaster!',
          imageUrl: 'https://i.ibb.co/KDjVYTV/WHINK-The-Original-Hair-Clog-Blaster-price-28-quantity-1.jpg',
          price: 28.00,
          shipping: 0,
          quantity: 999,
          description: 'WHINK The Original Hair Clog Blaster! 18oz. Liquid drain clog remover',
          title: 'household',
        },
        {
          id: 52,
          name: 'The Works Toilet Bowl Cleaner',
          imageUrl: 'https://i.ibb.co/bXF576n/The-Works-Toilet-Bowl-Cleaner-Pack-Of-4.jpg',
          price: 45.00,
          shipping: 0,
          quantity: 999,
          description: 'The Works Toilet Bowl Cleaner (Pack Of 4). Alcohol-Free Disinfectant and Toilet Bowl Cleaner.',
          title: 'household',
        },
        {
            id: 53,
            name: 'Sharper Image Percussion Massager',
            imageUrl: 'https://i.ibb.co/Dr1RTz9/Sharper-Image-Percussion-Pro-Deep-Tissue-Massager.jpg',
            price: 65.00,
            shipping: 0,
            quantity: 999,
            description: 'Sharper Image Percussion Pro Deep Tissue Massager - Black. 4 Hours of Battery Life. Weight: 4.2 lbs.',
            title: 'household',
        },
        {
          id: 54,
          name: 'Muze Thunder Wireless Speaker',
          imageUrl: 'https://i.ibb.co/Q9mXCQr/Muze-Thunder-Wireless-Portable-Party-Speaker-With-Bluetooth.jpg',
          price: 35.00,
          shipping: 0,
          quantity: 999,
          description: 'Muze Thunder Wireless Portable Party Speaker With Bluetooth. NEW.',
          title: 'household',
        },
        {
          id: 55,
          name: "Children's 3 PC Twin Sheet Set",
          imageUrl: 'https://i.ibb.co/mtxw5dw/Children-s-Bedsheets-LOL-SURPRISE-3-PC-Twin-Super-Soft-Sheet-Set.jpg',
          price: 34.80,
          shipping: 0,
          quantity: 999,
          description: 'LOL SURPRISE 3 PC Twin Super Soft Sheet Set. Material: Polyester. NEW.',
          title: 'household',
        },
        {
            id: 56,
            name: "Boy's Batman School Backpack",
            imageUrl: 'https://i.ibb.co/BBsx5VV/Batman-Boy-s-School-Backpack.jpg',
            price: 21.80,
            shipping: 0,
            quantity: 999,
            description: "Batman Boy's School Backpack. DC Comics Brute Force Boys - Black. Height: 17 inches. Width: 12 inches.",
            title: 'household',
        }
      ]
    }
  ];
  
export default PRODUCT_DATA;